baseURL = "https://blackpine.io/"
languageCode = "en-us"
title = "blackpine.io"

theme = "hugo_theme_pickles"
copyright = "&copy; Daniel Rammer 2021"

[params]
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "a collection of ramblings and general debauchery"

  paginate = 5

  instagram = "dan.rammer"
  github = "hamersaw"
  strava = "61166744"

  # Disqus shortname
  disqus = "blackpine-io"

  #author = "Your Name"
  #authorwebsite = "example.com"
  #avatar = "/path/to/avatar"
  #contact = "Your contact link (ex. mailto:foo@example.com)"
  #bio = "Your short bio"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
