baseURL = "https://blackpine.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "blackpine.io"

# https://github.com/Fastbyte01/KeepIt
theme = "KeepIt"

paginate = 5
enableRobotsTXT = true
#googleAnalytics = ""
disqusShortname = "blackpine-io"

#[sitemap]
#    changefreq = "monthly"
#    filename = "sitemap.xml"
#    priority = 0.5

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true

[menu]
    [[menu.posts]]
        name = "Posts"
        url = "/posts/"
        weight = 1

    [[menu.posts]]
        name = "Tags"
        url = "/tags/"
        weight = 2

    #[[menu.main]]
    #    name = "About"
    #    url = "/about"
    #    weight = 1

    #[[menu.main]]
    #    name = "Resume"
    #    url = "/resume.pdf"
    #    weight = 2

    [[menu.main]]
        name = "Curriculum Vitae"
        url = "/curriculum-vitae.pdf"
        weight = 3

    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 5

    [[menu.main]]
        name = "Publications"
        url = "/publications"
        weight = 6

[params]
    since = 2020
    author = "Daniel Rammer"
    subtitle = "PhD Student at Colorado State University"
    #home_mode = "profile" # post or other
    home_mode = "post" # post or other

    avatar = "/avatar.png"
    #avatar = "/images/me/avatar.jpeg"
    socialShare = true

    #description = "blah blah" # site description
    #keywords = "eh" # site keywords

    #license = 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    Email = "hamersaw@protonmail.com"
    GitHub = "hamersaw"
    Googlescholar = "zq3ow-8AAAAJ"
    Instagram = "dan.rammer"
    Strava = "61166744"

[params.share]
    #Email = true
    #GitHub = true
    #Insagram = true
    #Strava = true

[author]
  name = "Daniel Rammer"

  [params.publisher]
    name = "Daniel Rammer"
